---
title: "sizecolumn"
author: "Ishana Narayanan"
date: "October 29, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## open the data
```{r}
google <- read.csv("googleplaystore.csv")
str(google)
```

## extract the numeric part from Size
```{r}
# change Size from a factor to a character so we can use strsplit
google$Size <- as.character(google$Size)

# splitting the variable by "M"
numz <- unlist(strsplit(google$Size, "M"))
```

## create temp df so that you can keep track of if it is "M" or "k"
```{r}
# creating a temporary dataframe
temp_df <- as.data.frame(cbind(as.character(numz), 1000000))

# changing types so we can work with the vectorz
temp_df$V1 <- as.character(temp_df$V1)
temp_df$V2 <- as.numeric(as.character(temp_df$V2))

# if the first column has a "k" in it make the second column = 1000
temp_df$V2[grepl("k", temp_df$V1)] <- 1000

# remove the "k" from the first column
temp_df$V1 <- unlist(strsplit(temp_df$V1, "k"))
```

## multiply two columns together so you get new numeric value!!!
```{r}
# change "Varies with device" to NA
temp_df$V1[temp_df$V1 == "Varies with device"] <- NA

# change first column to numeric
temp_df$V1 <- as.numeric(as.character(temp_df$V1))

# multiply two columns
newvals <- temp_df$V1*temp_df$V2
```

## change NAs to mean value for category
```{r}
# install.pacakges("dplyr") # do this if you haven't installed the package!!!
library(dplyr)

google$Size <- newvals
google$Category <- as.character(google$Category)
unique(google$Category)

# temporary dataframe so that i don't fuck up the original one
yo <- google

# table of means per category
meanz <- google %>% group_by(Category) %>% summarize(Mean = mean(Size, na.rm=TRUE))
meanz$Category <- as.character(meanz$Category)

# iterate through each category and replace NA for that category with the mean value for that category
for(i in 2:nrow(meanz)) {
  temp <- yo[yo$Category == meanz[2,1],]
  temp$Size[is.na(temp$Size)] <- meanz[2,2]
  temp$Size <- unlist(temp$Size)
  yo$Size <- temp$Size
}
```

## write that shit as a CSV
```{r}
write.csv(yo, "googlenewbitch.csv", row.names = F)
```


